### ISSUE TITLE
Example has a link issue

### ISSUE THREAD

**Issue by lkocman** [openSUSE/md2workflow#1]
lkocman@linux-i0y4:~> md2workflow --env XXX /usr/share/md2workflow/example/my_project.conf 
INFO:md2workflow.cli:Using JIRA Backend. JIRA Server is http://lutoslawski.arch.suse.de:8080. Changes will be commited.
WARNING:md2workflow.cli:jira_session: Using insecure connection.
INFO:md2workflow.cli:Created issue Project config - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5186
INFO:md2workflow.cli:Assigning task Project config to None 
INFO:md2workflow.cli:Created issue Setup project - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5187
INFO:md2workflow.cli:Assigning task Setup project to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5187 under epic RMCT-5186
INFO:md2workflow.cli:Created issue Setup project in OBS - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5188
INFO:md2workflow.cli:Assigning task Setup project in OBS to lkocman 
INFO:md2workflow.cli:Adding relation from a task definition from Test setup to Setup project
INFO:md2workflow.cli:Adding relation Test setup Depends on Setup project
INFO:md2workflow.cli:Created issue Test setup - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5189
INFO:md2workflow.cli:Assigning task Test setup to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5189 under epic RMCT-5186
INFO:md2workflow.cli:Creating JIRA issue link 'Test setup' Depends on 'Setup project'
INFO:md2workflow.cli:Created issue Alpha phase - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5190
INFO:md2workflow.cli:Assigning task Alpha phase to None 
INFO:md2workflow.cli:Created issue Beta flag - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5191
INFO:md2workflow.cli:Assigning task Beta flag to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5191 under epic RMCT-5190
WARNING:md2workflow.cli:Could not find task with summary 'Beta flag'
WARNING:md2workflow.cli:Could not find task with summary 'Beta flag'
INFO:md2workflow.cli:Adding relation from a task definition from Test Beta flag to Beta flag
INFO:md2workflow.cli:Adding relation Test Beta flag Depends on Beta flag
INFO:md2workflow.cli:Created issue Test Beta flag - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5192
INFO:md2workflow.cli:Assigning task Test Beta flag to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5192 under epic RMCT-5190
INFO:md2workflow.cli:Created issue Setup delivery for partners - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5193
INFO:md2workflow.cli:Assigning task Setup delivery for partners to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5193 under epic RMCT-5190
INFO:md2workflow.cli:Adding relation from conf Depends On to <md2workflow.backend.jirabackend.JiraBasedProject object at 0x7fe4c92dde48>
INFO:md2workflow.cli:Adding relation Project config Depends On Alpha phase
INFO:md2workflow.cli:Creating JIRA issue link 'Project config' Depends On 'Alpha phase'
INFO:md2workflow.cli:Creating JIRA issue link 'Test setup' Depends on 'Setup project'
INFO:md2workflow.cli:Creating JIRA issue link 'Test Beta flag' Depends on 'Beta flag'
INFO:md2workflow.cli:Created issue Alpha 1 - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5194
INFO:md2workflow.cli:Assigning task Alpha 1 to None 
INFO:md2workflow.cli:Created issue Process all incomming submissions - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5195
INFO:md2workflow.cli:Assigning task Process all incomming submissions to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5195 under epic RMCT-5194
WARNING:md2workflow.cli:Could not find task with summary 'Process all incomming submissions'
WARNING:md2workflow.cli:Could not find task with summary 'Process all incomming submissions'
WARNING:md2workflow.cli:Could not find task with summary 'Process all incomming submissions'
WARNING:md2workflow.cli:Could not find task with summary 'Process all incomming submissions'
INFO:md2workflow.cli:Adding relation from a task definition from Product build to Process all incomming submissions
INFO:md2workflow.cli:Adding relation Product build Depends on Process all incomming submissions
INFO:md2workflow.cli:Created issue Product build - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5196
INFO:md2workflow.cli:Assigning task Product build to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5196 under epic RMCT-5194
WARNING:md2workflow.cli:Could not find task with summary 'Product build'
WARNING:md2workflow.cli:Could not find task with summary 'Product build'
WARNING:md2workflow.cli:Could not find task with summary 'Product build'
WARNING:md2workflow.cli:Could not find task with summary 'Product build'
INFO:md2workflow.cli:Adding relation from a task definition from Test Product build to Product build
INFO:md2workflow.cli:Adding relation Test Product build Depends on Product build
INFO:md2workflow.cli:Created issue Test Product build - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5197
INFO:md2workflow.cli:Assigning task Test Product build to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5197 under epic RMCT-5194
WARNING:md2workflow.cli:Could not find task with summary 'Test Product build'
WARNING:md2workflow.cli:Could not find task with summary 'Test Product build'
WARNING:md2workflow.cli:Could not find task with summary 'Test Product build'
WARNING:md2workflow.cli:Could not find task with summary 'Test Product build'
INFO:md2workflow.cli:Adding relation from a task definition from Release Product build to Test Product build
INFO:md2workflow.cli:Adding relation Release Product build Depends on Test Product build
INFO:md2workflow.cli:Created issue Release Product build - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5198
INFO:md2workflow.cli:Assigning task Release Product build to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5198 under epic RMCT-5194
INFO:md2workflow.cli:Adding relation from conf Implements to <md2workflow.backend.jirabackend.JiraBasedProject object at 0x7fe4c92dde48>
INFO:md2workflow.cli:Adding relation Alpha 1 Implements Alpha phase
INFO:md2workflow.cli:Creating JIRA issue link 'Project config' Depends On 'Alpha phase'
INFO:md2workflow.cli:Creating JIRA issue link 'Alpha 1' Implements 'Alpha phase'
INFO:md2workflow.cli:Creating JIRA issue link 'Test setup' Depends on 'Setup project'
INFO:md2workflow.cli:Creating JIRA issue link 'Test Beta flag' Depends on 'Beta flag'
INFO:md2workflow.cli:Creating JIRA issue link 'Product build' Depends on 'Process all incomming submissions'
INFO:md2workflow.cli:Creating JIRA issue link 'Test Product build' Depends on 'Product build'
INFO:md2workflow.cli:Creating JIRA issue link 'Release Product build' Depends on 'Test Product build'
	INFO:md2workflow.cli:Created issue Beta Phase - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5199
INFO:md2workflow.cli:Assigning task Beta Phase to None 
INFO:md2workflow.cli:Created issue Test delivery repositories - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5200
INFO:md2workflow.cli:Assigning task Test delivery repositories to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5200 under epic RMCT-5199
INFO:md2workflow.cli:Created issue Prepare Beta release notes - http://lutoslawski.arch.suse.de:8080/browse/RMCT-5201
INFO:md2workflow.cli:Assigning task Prepare Beta release notes to lkocman 
INFO:md2workflow.cli:Added issue RMCT-5201 under epic RMCT-5199
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
INFO:md2workflow.cli:Adding relation from conf Depends On to <md2workflow.backend.jirabackend.JiraBasedProject object at 0x7fe4c92dde48>
INFO:md2workflow.cli:Adding relation Alpha Phase Depends On Beta Phase
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
WARNING:md2workflow.cli:Could not find task with summary 'Alpha Phase'
Traceback (most recent call last):
  File "/usr/bin/md2workflow", line 11, in <module>
    load_entry_point('md2workflow==1.4.3', 'console_scripts', 'md2workflow')()
  File "/usr/lib/python3.7/site-packages/md2workflow/cli.py", line 221, in main
    client.handle_project(args[0])
  File "/usr/lib/python3.7/site-packages/md2workflow/cli.py", line 155, in handle_project
    md2workflow.backend.jirabackend.handle_project(self)
  File "/usr/lib/python3.7/site-packages/md2workflow/backend/jirabackend.py", line 472, in handle_project
    project.publish_task_relations()
  File "/usr/lib/python3.7/site-packages/md2workflow/backend/jirabackend.py", line 378, in publish_task_relations
    super(JiraBasedProject, self).publish_task_relations()
  File "/usr/lib/python3.7/site-packages/md2workflow/workflow.py", line 361, in publish_task_relations
    self._replace_task_placeholders()
  File "/usr/lib/python3.7/site-packages/md2workflow/workflow.py", line 262, in _replace_task_placeholders
    i].source.summary
AssertionError: Relations: Could not find task with summary 'Alpha Phase'

**Comment by lkocman** [comment]
This is already resolved
